@include('commons.textfield', ['obj' => $supplier, 'name' => 'name', 'label' => _i('Nome'), 'mandatory' => true])
@include('commons.textfield', ['obj' => $supplier, 'name' => 'business_name', 'label' => _i('Ragione Sociale')])
@include('commons.textarea', ['obj' => $supplier, 'name' => 'description', 'label' => _i('Descrizione'), 'maxlength' => 500])
@include('commons.textfield', ['obj' => $supplier, 'name' => 'taxcode', 'label' => _i('Codice Fiscale')])
@include('commons.textfield', ['obj' => $supplier, 'name' => 'vat', 'label' => _i('Partita IVA')])
@include('commons.textarea', ['obj' => $supplier, 'name' => 'payment_method', 'label' => _i('Modalità Pagamento')])
@include('commons.textarea', ['obj' => $supplier, 'name' => 'order_method', 'label' => _i('Modalità Avanzamento Ordini')])
