@include('commons.textfield', ['obj' => $supplier, 'name' => 'name', 'label' => 'Nome', 'mandatory' => true])
@include('commons.textarea', ['obj' => $supplier, 'name' => 'description', 'label' => 'Descrizione'])
@include('commons.textfield', ['obj' => $supplier, 'name' => 'taxcode', 'label' => 'Codice Fiscale'])
@include('commons.textfield', ['obj' => $supplier, 'name' => 'vat', 'label' => 'Partita IVA'])
@include('commons.textarea', ['obj' => $supplier, 'name' => 'payment_method', 'label' => 'Modalità Pagamento'])
@include('commons.textarea', ['obj' => $supplier, 'name' => 'order_method', 'label' => 'Modalià Avanzamento Ordini'])
