<?php

return array (
  'help' => 
  array (
    'mandatory_column_error' => 'Mandatory column not specified',
    'importing' => 
    array (
      'deliveries' => 
      array (
        'first_product' => 'Use this item to identify the first product in the list',
      ),
      'user' => 
      array (
        'aggregation' => 'If specified, have to include the name of one of the Groups in the "Configurations" panel for this Aggregation',
        'deleted' => 'Choose ‘true’ or ‘false’',
        'balance' => 'Warning! Use this attribute only for initial import of users, and only for new users, or balances will be incoherent!',
        'instruction' => 'If the username already exists, the user will be updated wth data from this file. Otherwise, an invitation email will be sent with the link to access the first time and choose own password.',
      ),
    ),
    'csv_instructions' => 'Only CSV files are allowed. It is recommended to format your table in a homogeneous way, with no merged cells, empty cells, headers: each row must contain all information about the subject. Prices and sums must be expressed without the euro sign.',
    'selection_instructions' => 'Once the file is uploaded, it will be possible to specify which attribute represents each column found in the document.',
    'img_csv_instructions' => '',
  ),
  'importing' => 
  array (
    'deliveries' => 
    array (
      'first_product' => 'First product',
      'instruction' => 'From here, you can re-import a CSV file generated by the "Order Summary Table" function, after manually processing it with the quantities delivered for each user.',
      'notice' => '',
      'product_error' => 'Unidentified product: :name',
      'order_error' => 'Unidentified order',
      'done' => 'Imported deliveries',
    ),
  ),
  'balance_csv_filename' => 'Balance export :date.csv',
  'products_list_filename' => 'Price list :supplier.:format',
  'import' => 
  array (
    'csv' => 'Import CSV',
    'gdxp' => 'Import GDXP',
  ),
  'help_csv_libreoffice' => 'For viewing and editing CSV (<i> Comma-Separated Values</i>) files, we recommended <a target="_blank" href="http://it.libreoffice.org/">LibreOffice</a> .',
  'data' => 
  array (
    'columns' => 'Columns',
    'format' => 'Format',
    'formats' => 
    array (
      'pdf' => 'PDF',
      'csv' => 'CSV',
      'gdxp' => 'GDXP',
    ),
    'status' => 'Reservation Status',
    'users' => 'Users\' Data',
    'products' => 'Product Columns',
    'split_friends' => '',
  ),
  'export' => 
  array (
    'database' => 'Database export',
  ),
  'help_split_friends' => '',
  'help_aggregate_export_summary' => '',
  'flags' => 
  array (
    'include_unbooked' => '',
  ),
  'do_balance' => '',
  'movements_heading' => '',
  'accepted_columns' => '',
);